version: "3.8"

services:
  app:
    build: .
    container_name: storybooks-app
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/storybooks
      - NODE_ENV=development
    volumes:
      - .:/usr/src/app
    restart: unless-stopped

  mongo:
    image: mongo:5
    container_name: storybooks-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped

volumes:
  mongo-data:
